name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Hassfest Validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master